// ⚠️ AUTO-GENERATED by apps/cms/scripts/gen-cache-tags.ts — DO NOT EDIT MANUALLY
// Chạy: pnpm --filter cms run gen:cache-tags
//
// Source of truth: Payload collection configs (relationship fields)
// Excluded (custom.cacheable: false): media, leads, templates

// ── Collection-level tags ────────────────────────────────────────────
export const COLLECTION_TAGS = {
  users: "users",
  apartments: "apartments",
  landingPages: "landing-pages",
  locations: "locations",
  tags: "tags",
  translations: "translations",
  amenities: "amenities",
} as const;

export type CollectionTag = (typeof COLLECTION_TAGS)[keyof typeof COLLECTION_TAGS];

// ── Reverse dependency map (transitive closure via BFS) ──────────
// Khi collection X thay đổi → cascade purge TẤT CẢ collections phụ thuộc
// (trực tiếp + gián tiếp). Auto-derived từ Payload relationship fields.
export const REVERSE_DEPS: Readonly<Record<string, readonly CollectionTag[]>> = {
  [COLLECTION_TAGS.tags]: [COLLECTION_TAGS.apartments, COLLECTION_TAGS.landingPages],
  [COLLECTION_TAGS.locations]: [COLLECTION_TAGS.apartments, COLLECTION_TAGS.landingPages],
  [COLLECTION_TAGS.amenities]: [COLLECTION_TAGS.apartments, COLLECTION_TAGS.landingPages],
  [COLLECTION_TAGS.users]: [COLLECTION_TAGS.apartments, COLLECTION_TAGS.landingPages],
  [COLLECTION_TAGS.apartments]: [COLLECTION_TAGS.landingPages],
};

// ── External source tags (không phải Payload collection) ───────────
export const EXCHANGE_RATE_TAG = "exchange-rate";

