/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'landing-pages': LandingPage;
    media: Media;
    apartments: Apartment;
    leads: Lead;
    templates: Template;
    translations: Translation;
    amenities: Amenity;
    tags: Tag;
    locations: Location;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'landing-pages': LandingPagesSelect<false> | LandingPagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    apartments: ApartmentsSelect<false> | ApartmentsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    templates: TemplatesSelect<false> | TemplatesSelect<true>;
    translations: TranslationsSelect<false> | TranslationsSelect<true>;
    amenities: AmenitiesSelect<false> | AmenitiesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('vi' | 'en') | ('vi' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'vi' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  brandName: string;
  /**
   * Logo to display instead of initials
   */
  logo?: (number | null) | Media;
  agentSlug: string;
  verified?: boolean | null;
  profile?: {
    experienceYears?: number | null;
    successfulTransactions?: number | null;
    phoneNumber?: string | null;
    zaloUrl?: string | null;
  };
  role?: ('admin' | 'agent') | null;
  subscription?: {
    tier?: ('free' | 'pro') | null;
    expiresAt?: string | null;
    lastPaymentId?: string | null;
  };
  theme?: {
    primaryColor?: string | null;
    secondaryColor?: string | null;
    secondaryForegroundColor?: string | null;
    borderRadius?: ('none' | 'sm' | 'md' | 'lg' | 'full') | null;
    fontFamily?: ('sans' | 'serif') | null;
  };
  usage?: {
    storageBytes?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  owner: number | User;
  cloudinaryPublicId?: string | null;
  cloudinaryURL?: string | null;
  cloudinaryResourceType?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages".
 */
export interface LandingPage {
  id: number;
  templateSelection?: (number | null) | Template;
  owner: number | User;
  blocks?:
    | (
        | {
            title: string;
            subtitle?: string | null;
            backgroundImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroBanner';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            avatar?: (number | null) | Media;
            agentName?: string | null;
            agentTitle?: string | null;
            phoneNumber?: string | null;
            zaloLink?: string | null;
            experienceYears?: number | null;
            successfulDeals?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutAgent';
          }
        | {
            apartmentsFilter?: (number | Apartment)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'listApartments';
          }
        | {
            title?: string | null;
            placeholder?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: number;
  title: string;
  blocks?:
    | (
        | {
            title: string;
            subtitle?: string | null;
            backgroundImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroBanner';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            avatar?: (number | null) | Media;
            agentName?: string | null;
            agentTitle?: string | null;
            phoneNumber?: string | null;
            zaloLink?: string | null;
            experienceYears?: number | null;
            successfulDeals?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutAgent';
          }
        | {
            apartmentsFilter?: (number | Apartment)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'listApartments';
          }
        | {
            title?: string | null;
            placeholder?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apartments".
 */
export interface Apartment {
  id: number;
  listingType: 'sale' | 'rent';
  /**
   * Free-form type & labels
   */
  tags?: (number | Tag)[] | null;
  title: string;
  address?: string | null;
  gallery?: (number | Media)[] | null;
  /**
   * Auto-filled from first gallery image if left empty
   */
  thumbnail?: (number | null) | Media;
  tourUrl?: string | null;
  keyFacts?: {
    area?: number | null;
    bedrooms?: number | null;
    bathrooms?: number | null;
  };
  price?: number | null;
  /**
   * Auto-synced from Listing Type (Sale = total, Rent = per month)
   */
  priceUnit?: ('total' | 'per_month') | null;
  location?: {
    /**
     * Chọn phường/xã cụ thể (VD: Thảo Điền, Phường 1...)
     */
    region?: (number | null) | Location;
    /**
     * Dán link embed từ Google Maps (VD: https://www.google.com/maps/embed?pb=...)
     */
    mapEmbedUrl?: string | null;
    amenities?: (number | Amenity)[] | null;
  };
  sections?:
    | {
        title: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  slug?: string | null;
  owner: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  title: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  title: string;
  level: 'city' | 'district' | 'ward';
  parent?: (number | null) | Location;
  slug?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities".
 */
export interface Amenity {
  id: number;
  title: string;
  /**
   * Phosphor Icon component name (e.g., "SwimmingPool", "Barbell")
   */
  icon: string;
  category: 'internal' | 'external';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  owner: number | User;
  apartmentRef?: (number | null) | Apartment;
  type: 'sale' | 'rent' | 'consignment';
  message?: string | null;
  status?: ('new' | 'contacted' | 'closed' | 'lost') | null;
  deleted?: boolean | null;
  dedupeWarning?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage localization strings for the frontend.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translations".
 */
export interface Translation {
  id: number;
  /**
   * Key format: namespace.key (e.g. hero.title)
   */
  key: string;
  value: string;
  namespace?: ('common' | 'hero' | 'nav' | 'footer' | 'apartments' | 'agent' | 'contact') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'landing-pages';
        value: number | LandingPage;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'apartments';
        value: number | Apartment;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'templates';
        value: number | Template;
      } | null)
    | ({
        relationTo: 'translations';
        value: number | Translation;
      } | null)
    | ({
        relationTo: 'amenities';
        value: number | Amenity;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  brandName?: T;
  logo?: T;
  agentSlug?: T;
  verified?: T;
  profile?:
    | T
    | {
        experienceYears?: T;
        successfulTransactions?: T;
        phoneNumber?: T;
        zaloUrl?: T;
      };
  role?: T;
  subscription?:
    | T
    | {
        tier?: T;
        expiresAt?: T;
        lastPaymentId?: T;
      };
  theme?:
    | T
    | {
        primaryColor?: T;
        secondaryColor?: T;
        secondaryForegroundColor?: T;
        borderRadius?: T;
        fontFamily?: T;
      };
  usage?:
    | T
    | {
        storageBytes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages_select".
 */
export interface LandingPagesSelect<T extends boolean = true> {
  templateSelection?: T;
  owner?: T;
  blocks?:
    | T
    | {
        heroBanner?:
          | T
          | {
              title?: T;
              subtitle?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        aboutAgent?:
          | T
          | {
              content?: T;
              avatar?: T;
              agentName?: T;
              agentTitle?: T;
              phoneNumber?: T;
              zaloLink?: T;
              experienceYears?: T;
              successfulDeals?: T;
              id?: T;
              blockName?: T;
            };
        listApartments?:
          | T
          | {
              apartmentsFilter?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              title?: T;
              placeholder?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  owner?: T;
  cloudinaryPublicId?: T;
  cloudinaryURL?: T;
  cloudinaryResourceType?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apartments_select".
 */
export interface ApartmentsSelect<T extends boolean = true> {
  listingType?: T;
  tags?: T;
  title?: T;
  address?: T;
  gallery?: T;
  thumbnail?: T;
  tourUrl?: T;
  keyFacts?:
    | T
    | {
        area?: T;
        bedrooms?: T;
        bathrooms?: T;
      };
  price?: T;
  priceUnit?: T;
  location?:
    | T
    | {
        region?: T;
        mapEmbedUrl?: T;
        amenities?: T;
      };
  sections?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  slug?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  owner?: T;
  apartmentRef?: T;
  type?: T;
  message?: T;
  status?: T;
  deleted?: T;
  dedupeWarning?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  title?: T;
  blocks?:
    | T
    | {
        heroBanner?:
          | T
          | {
              title?: T;
              subtitle?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        aboutAgent?:
          | T
          | {
              content?: T;
              avatar?: T;
              agentName?: T;
              agentTitle?: T;
              phoneNumber?: T;
              zaloLink?: T;
              experienceYears?: T;
              successfulDeals?: T;
              id?: T;
              blockName?: T;
            };
        listApartments?:
          | T
          | {
              apartmentsFilter?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              title?: T;
              placeholder?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translations_select".
 */
export interface TranslationsSelect<T extends boolean = true> {
  key?: T;
  value?: T;
  namespace?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities_select".
 */
export interface AmenitiesSelect<T extends boolean = true> {
  title?: T;
  icon?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  title?: T;
  level?: T;
  parent?: T;
  slug?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}